# Generated by Django 3.2.3 on 2021-05-29 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210530_0232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='amount',
        ),
    ]
